#!/usr/bin/python2.4
# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_ACTION_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='poker_bot.Action.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='FOLD', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CALL', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RAISE', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CHECK', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_EVENT_CARD_SUIT = descriptor.EnumDescriptor(
  name='Suit',
  full_name='poker_bot.Event.Card.Suit',
  filename='Suit',
  values=[
    descriptor.EnumValueDescriptor(
      name='DIAMONDS', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SPADES', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='HEARTS', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CLUBS', index=3, number=3,
      options=None,
      type=None),
  ],
  options=None,
)

_EVENT_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='poker_bot.Event.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='JOIN', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NEW_ROUND', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BUTTON', index=2, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BIG_BLIND', index=3, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='SMALL_BLIND', index=4, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DEAL', index=5, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='FLOP', index=6, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TURN', index=7, number=7,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='RIVER', index=8, number=8,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ACTION', index=9, number=9,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ADJUST_CREDITS', index=10, number=10,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='WIN', index=11, number=11,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='END_OF_ROUND', index=12, number=12,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='QUIT', index=13, number=13,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='BAD_BOT', index=14, number=14,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='YOUR_TURN', index=15, number=15,
      options=None,
      type=None),
  ],
  options=None,
)


_ACTION = descriptor.Descriptor(
  name='Action',
  full_name='poker_bot.Action',
  filename='protocol/poker_bot.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='poker_bot.Action.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount', full_name='poker_bot.Action.amount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _ACTION_TYPE,
  ],
  options=None)


_EVENT_CARD = descriptor.Descriptor(
  name='Card',
  full_name='poker_bot.Event.Card',
  filename='protocol/poker_bot.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='value', full_name='poker_bot.Event.Card.value', index=0,
      number=1, type=5, cpp_type=1, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='suit', full_name='poker_bot.Event.Card.suit', index=1,
      number=2, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _EVENT_CARD_SUIT,
  ],
  options=None)

_EVENT = descriptor.Descriptor(
  name='Event',
  full_name='poker_bot.Event',
  filename='protocol/poker_bot.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='poker_bot.Event.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='player_id', full_name='poker_bot.Event.player_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='credits', full_name='poker_bot.Event.credits', index=2,
      number=3, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='amount', full_name='poker_bot.Event.amount', index=3,
      number=4, type=5, cpp_type=1, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='cards', full_name='poker_bot.Event.cards', index=4,
      number=5, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='card', full_name='poker_bot.Event.card', index=5,
      number=6, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='poker_bot.Event.action', index=6,
      number=7, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='rank', full_name='poker_bot.Event.rank', index=7,
      number=8, type=13, cpp_type=3, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='message', full_name='poker_bot.Event.message', index=8,
      number=10, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _EVENT_TYPE,
  ],
  options=None)


_ACTION.fields_by_name['type'].enum_type = _ACTION_TYPE
_EVENT_CARD.fields_by_name['suit'].enum_type = _EVENT_CARD_SUIT
_EVENT.fields_by_name['type'].enum_type = _EVENT_TYPE
_EVENT.fields_by_name['cards'].message_type = _EVENT_CARD
_EVENT.fields_by_name['card'].message_type = _EVENT_CARD
_EVENT.fields_by_name['action'].message_type = _ACTION

class Action(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTION

class Event(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Card(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _EVENT_CARD
  DESCRIPTOR = _EVENT

